defaults:
  - model: baseline
  - writer: wandb
  - metrics: asvspoof
  - datasets: asvspoof
  - dataloader: main
  - transforms: main
  - _self_

optimizer:
  _target_: torch.optim.Adam
  lr: 3e-4

lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  gamma: 0.5
  step_size: 10

loss_function:
  _target_: torch.nn.CrossEntropyLoss

trainer:
  log_step: 50
  n_epochs: 100
  epoch_len: 500
  device_tensors:
    - data_object
    - labels
  resume_from: null
  device: auto
  override: false
  monitor: off
  save_period: 5
  early_stop: ${trainer.n_epochs}
  save_dir: saved
  seed: 1